safe: true
exclude: [ "node_modules", "tutorial", "_build", "_run", "_watch", "Gemfile", "Gemfile.lock", "LICENSE", "package.json", "README.md", "style.scss", "TODO", "Vagrantfile" ]
markdown: kramdown
